worker_processes 1;
error_log stderr debug;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /dev/stdout main;

    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 10M;

    server {
        listen 80;
        server_name localhost;

        # Метрики для Prometheus
        location /metrics {
            stub_status on;
            access_log off;
            allow all;
        }

        # Health check
        location /health {
            return 200 '{"status": "ok"}';
            add_header Content-Type application/json;
        }

        # Публичные endpoints
        location /register {
            proxy_pass http://security:5000/v1/user;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Content-Type $content_type;
        }

        location /token {
            proxy_pass http://security:5000/v1/token;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Content-Type $content_type;
        }

        # Защищенные endpoints
        location /user {
            auth_request /auth;
            proxy_pass http://security:5000/v1/user;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Type $content_type;
        }

        location /upload {
            auth_request /auth;
            client_max_body_size 10M;
            proxy_pass http://uploader:5001/v1/upload;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Type $content_type;
        }

        location /images/ {
            auth_request /auth;
            proxy_pass http://minio:9000/images/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

         #  proxy_set_header Authorization "Basic bWluaW9hZG1pbjptaW5pb2FkbWlu";

            proxy_pass_header Content-Type;
            proxy_pass_header Content-Length;
            proxy_buffering off;
        }

        # Внутренний endpoint для проверки токена
        location = /auth {
            internal;
            proxy_pass http://security:5000/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_body "";
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Type "application/json";
        }
    }
}